services:
  studify-nginx:
    container_name: studify-nginx
    restart: always
    build: .
    ports:
      - "80:80"
    networks:
      - mikrus-net
    volumes:
      - ./html/poradnik:/var/www/poradnik

networks:
  mikrus-net:
    external: true